# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4WiXrnC6wc_2PWnY--6uEscXHVzuBg9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



"""Q.1- Which region is generating the highest revenue, and which region is generating the lowest?

Q.2- What is the monthly trend of revenue, which months have faced the biggest increase/decrease?

Q.3- Which months generated the most revenue? Is there a seasonality in sales?

Q.4- Who are the top customers and how much do they contribute to the total revenue? Is the business
dependent on these customers or is the customer base diversified?

"""

path = "/content/drive/MyDrive/Datasets/Online Retail.xlsx"
df = pd.read_excel(path)

from google.colab import drive
drive.mount('/content/drive')

df

df.shape



df.isnull().sum()

df.info()

df["CustomerID"] = df["CustomerID"].astype(str)

df.loc[df["CustomerID"].str.contains("n",case=False)]

df.columns

df["Revenue"] = df["UnitPrice"] * df["Quantity"]

df.head()

df1 = df.groupby("Country",as_index=False)["Revenue"].sum()

df1.nlargest(1,columns="Revenue")

df1.nsmallest(1,columns="Revenue")

df.head()

df["Month"] = df["InvoiceDate"].dt.month

df.head()

df2=df.groupby("Month",as_index=False)["Revenue"].sum()

Total_Revenue = df2["Revenue"].sum()

df2["Percent_Rev"] = df2["Revenue"].apply(lambda x: (x/Total_Revenue)*100)

df2.nlargest(12,columns="Percent_Rev")

l = np.arange(1,13)

b = df2["Percent_Rev"]

l

plt.bar(l,b)
plt.xticks(l)

df2.nsmallest(2,columns="Revenue")

df2.plot(x="Month",y="Revenue")

plt.plot(l,b,marker="8",mfc="k",mec="k",c="g")
plt.grid()
plt.xlabel("Months")
plt.ylabel("Percent")

df3 = df.copy()

df3.head(2)

from statsmodels.tsa.seasonal import seasonal_decompose
df3.sort_index(inplace=True)
df3.set_index('InvoiceDate', inplace=True)


analysis = df3[['Revenue']].copy()

# Remove negative values from the `Revenue` column
analysis['Revenue'] = analysis['Revenue'].clip(lower=0)

decompose_result_mult = seasonal_decompose(analysis, model="additive" , period=7)

trend = decompose_result_mult.trend
seasonal = decompose_result_mult.seasonal
residual = decompose_result_mult.resid

decompose_result_mult.plot();





df.isnull().sum()

df.columns

df.columns

df["InvoiceDate"].unique()

Q.4- Who are the top customers and how much do they contribute to the total revenue? Is the business dependent on these customers or is the customer base diversified?

df

df

df1 = df.groupby("CustomerID",as_index=False)["Revenue"].sum()

df1.nlargest(5,columns="Revenue")



Total_Revenue = df["Revenue"].sum()

Total_Revenue

df1["Percent_Rev"] = df["Revenue"].apply(lambda x: (x/Total_Revenue)*100)

df2=df1.nlargest(5,columns="Revenue")

df2["Percent_Rev"].sum()

df["CustomerID"] = df["CustomerID"].astype(str)

df.loc[df["CustomerID"].str.contains("n",case=True)]

df.loc[df["InvoiceNo"]==536544]["CustomerID"].value_counts()